In [1]:
import numpy

In [9]:
array = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array.shape)
array

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
cube = numpy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube.shape)
cube

(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
# Numpy implicitně nedělá maticové násobení, protože to není knihovna na matice, ale n-rozměrná pole
array * numpy.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

In [12]:
# Rychlejší indexování pomocí tuple
array[0, 1]

2

In [13]:
# Výběr prvků pravdivostní tabulkou
array[array > 4]

array([5, 6, 7, 8, 9])

In [14]:
# Výběr řádků z pole
array[[0, 1, 1, 2]]

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Výběr řádků a sloupců
array[[0, 1, 1, 2], 1]

array([2, 5, 5, 8])

In [19]:
# Násobení jednotlivých sloupců
print(array * [0, 2, 4])

# Násobení celých řádků
array * [[0], [2], [4]]

[[ 0  4 12]
 [ 0 10 24]
 [ 0 16 36]]


array([[ 0,  0,  0],
       [ 8, 10, 12],
       [28, 32, 36]])

In [21]:
array[array > 4] = 666
array

array([[  1,   2,   3],
       [  4, 666, 666],
       [666, 666, 666]])

In [ ]:
# Lepší metoda - rychlejší a netvoří duplikát
array *= 2
print(array)

array = array * 2
array